[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200
upload_port = COM25

; Настройки Flash
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB

; РАЗДЕЛЫ
board_build.partitions = partitions.csv

; Настройки PSRAM
board_build.psram_mode = qio
board_build.psram_size = 8MB

; Папка с файлами для SPIFFS
board_upload.spiffs_data_dir = data

; Дополнительные флаги
board_build.extra_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1

build_flags = 
    -DCONFIG_ESP_WIFI_DEBUG_PRINT=1
    -DCONFIG_LOG_DEFAULT_LEVEL=3
    -I .pio/libdeps/esp32-s3-devkitc-1/cjson

; Зависимости
lib_deps = 
    cjson